### ISSUE TITLE
flickering tasklist when resizing with mouse

### ISSUE THREAD

**Issue by ptrxyz** [xinhaoyuan/layout-machi#18] opened 2022-06-09 20:32 UTC
I am using latest machi (master branch) with awesome 4.3, default config. I setup a 3 column layout (`3w.`). If I drag-move the middle client with `Mod`+`Mouse 1` to the right, while the mouse cursor is above the client on the 3, the taskbar flickers while dragging. It seems the taskbar "thinks" the active client would be the right one and thus renders that one brighter.

I tried to show what I mean in the attached video. See the taskbar on top.
https://user-images.githubusercontent.com/209056/172938951-4d9f4616-7932-40e2-902c-c1900ce57ea9.mp4

I really loooove this project, is there a thing we could do about this?

```
awesome v4.3-1356-g9895aeb0d (Too long)
 • Compiled against Lua 5.4.4 (running with 0.9.2)
 • API level: 4
 • D-Bus support: yes
 • xcb-errors support: no
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: /usr/share/lua/5.4/lgi/version.lua
 • Transparency enabled: yes
 • Custom search paths: no
```

**Comment by ptrxyz** [comment] 2022-06-09 21:11
I am not sure on anythin, but I think that the "list" event seems to get fired a lot:

https://github.com/awesomeWM/awesome/blob/3a542219f3bf129546ae79eb20e384ea28fa9798/lib/awful/widget/tasklist.lua#L678
This then triggers the tasklist updates:
https://github.com/awesomeWM/awesome/blob/3a542219f3bf129546ae79eb20e384ea28fa9798/lib/awful/widget/tasklist.lua#L619

Nor sure if this is helpful though.

**Comment by ptrxyz** [comment] 2022-06-09 21:21
Ok another thing: It seems the order of the clients changes while dragging. And this seems to cause the update for the tasklist.

I added a handler for the swap event and it seems to be called all the time.

```
client.connect_signal("swapped", function(c)
    print("~SWAP~", math.random())
end)
```

I tracked it back to this being fired: https://github.com/awesomeWM/awesome/blob/3a542219f3bf129546ae79eb20e384ea28fa9798/lib/awful/layout/init.lua#L385

I was able to work around the flickering by checking if the current layout's name is `~= "machi"` and returning early then. But I believe this more a dirty hack.

**Comment by xinhaoyuan** [comment] 2022-06-09 23:54
(I could not play the uploaded video in Firefox or mplayer - maybe the file was bad?)

This seems to be a duplicate of #9 - could you check if the same thing would happen when using the stock layouts?

**Comment by ptrxyz** [comment] 2022-06-10 08:07
I just checked, it doesn't to happen with stock layouts. In addition I uploaded the video to YouTube, I guess they know what they are doing with regard to encoding a video in a way that it's playable in browsers. :grinning: 

Find it here: https://youtu.be/JqcsOAXonsM

My workaround for now is that one line `if l ~= "machi" then return end` in the `layout.move_handler` function in `awesome/lib/awful/layout/init.lua`. It works, yet I don't know if it breaks something else and it requires a change to awesomeWM's source which I do not necessarily like.

I put the code here for reference:
```lua
--- Default handler for `request::geometry` signals for tiled clients with
-- the "mouse.move" context.
-- @tparam client c The client
-- @tparam string context The context
-- @tparam table hints Additional hints
-- @signalhandler awful.layout.move_handler
function layout.move_handler(c, context, hints) --luacheck: no unused args
    -- Quit if it isn't a mouse.move on a tiled layout, that's handled elsewhere
    if c.floating then return end
    if context ~= "mouse.move" then return end

    if capi.mouse.screen ~= c.screen then
        c.screen = capi.mouse.screen
    end


    local l = c.screen.selected_tag and c.screen.selected_tag.layout or nil
    if l == layout.suit.floating then return end
    -- work around flickering bug: return early if Machi layout
    if l.machi_set_cmd then return end

    local c_u_m = capi.mouse.current_client
    if c_u_m and not c_u_m.floating then
        if c_u_m ~= c then
            c:swap(c_u_m)
        end
    end
end
```

**Comment by xinhaoyuan** [comment] 2022-06-16 03:36
Thanks. It is indeed not very friendly to machi layouts. I added a fix - please let me know if the problem persists

**Closed as completed** 2022-06-16 03:35 UTC
