### ISSUE TITLE
machi layout not working properly

### ISSUE THREAD

**Issue by cherrynoize** [xinhaoyuan/layout-machi#22] opened 2023-03-29 15:56 UTC
I really don't know what's causing this but after I edit the `machi.default_layout` with `Super + .`  the layout does not change as expected. Instead current window (if any) fills the whole screen (unmaximized) portion, while all new windows get stacked in the first window area leaving the rest of the screen empty.

### Screnshot

![lots of windows stacked](https://i.imgur.com/nuT8uT1.png)

This is my layouts part:

    awful.layout.layouts = {
       machi.default_layout,
    l.floating,

And this is my keybindings:

    awful.key({ modkey,           }, ".",    function () machi.default_editor.start_interactive() end,
              {description = "edit current layout if machi layout", group = "layout"}),
    awful.key({ modkey,           }, "/",    function () machi.switcher.start(client.focus) end,
              {description = "switch between windows for a machi layout", group = "layout"}),

**Comment by xinhaoyuan** [comment] 2023-03-30 02:01
What's the layout command used in the editor?

**Comment by cherrynoize** [comment] 2023-04-03 15:33
Any, apparently.

**Comment by archion** [comment] 2023-08-20 07:02
same here on archlinux with awesome 4.3-3  (i.e. edit layout doesn't apply at all). The legacy branch doesn't have such issue but the swicher list is not correct. For now, the commit a651f5528e4bbddc3ce3de0a3c58afa8cb942dda works best for me with correct swicher list.

**Comment by xinhaoyuan** [comment] 2023-10-08 19:49
Sorry for the long delay. I'm very busy with my life and have limited time working on this.

I tried the newest commit (https://github.com/xinhaoyuan/layout-machi/commit/497d076903e6f5375c0456593f24adcca3db07e6) on the v4.3 branch of the official awesomewm repo. Editing/changing layout was working as intended - clients are moved to the closest areas from them. I don't use Arch so I don't know if any patches are applied.

Please try to provide more information if you still see the problem - ideally a demo video + logs, or a self-contained reproduction script.

**Comment by xinhaoyuan** [comment] 2023-10-08 19:50
Closing for now. Feel free to reopen with more details.

**Closed as completed by xinhaoyuan** 2023-10-08 19:50 UTC
